name: 🙋‍♂️ Playwright API Tests

on:
  push:
    branches: [ ci-fix ]
  pull_request:
    branches: [ ci-fix ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Load .env file so tests get the right environment variables
      - name: Load environment variables
        run: |
          cp .env.example .env # or copy your actual .env if safe
        shell: bash

      - name: Run API tests
        run: npx playwright test --config=playwright.config.ts
        env:
          $(cat .env | xargs)  # inject all variables from .env

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
